version: '3.1'

services:
  db:
    image: postgres
    container_name: db_postegres_webflux
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: GMT
    ports:
      - "54331:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data
    networks:
      - postgres_webflux_network
    restart: always


volumes:
  webflux_data:
networks:
  postgres_webflux_network:
    driver: bridge